version: "3.8"

services:
  server:
    image: cosmtrek/air:latest
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/mission-reward
    working_dir: /go/src/mission-reward
    environment:
      DB_ADDRESS: db
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mission_reward
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
