[general]
    verbose = true

[server]
    address = 'localhost'
    port = 8080

[db]
    driver =   "mysql"
    user =     "user"
    password = "password"
    database = "mission_reward"
    address  = "localhost"
    port = 3306

[test]
    db_port = 3307
